SIMPLE_NPCS_BETS              = 0.7
TAX_FOR_SIMPLE_BET            = 0
TAX_FOR_COMPOSITE_BET         = 0
ROUND_COINS                   = True

EFFECTIVE_RATIO_IN_WINNER_BET = 1.0
EFFECTIVE_RATIO_IN_PLACED_BET = 0.7
EFFECTIVE_RATIO_IN_THIRD_BET  = 0.4